language: node_js
node_js:
  - '0.10'
  - '0.11'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-xmc' ]; then cd .. && eval "mv $currentfolder generator-xmc" && cd generator-xmc; fi

before_script:
  - npm i coveralls istanbul mocha-lcov-reporter blanket

after_script:
  - npm run coveralls

script:
  - npm test
