language: node_js
node_js:
  - '0.10'
  - '0.11'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-xmc' ]; then cd .. && eval "mv $currentfolder generator-xmc" && cd generator-xmc; fi

before_script:
  - npm i coveralls istanbul

after_script:
  - NODE_ENV=test istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage

script:
  - npm test
